import json
import os

# Define the content of the Jupyter Notebook
notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# SDLC Automate API: Model Comparison (GPT vs Gemini)\n",
    "\n",
    "This notebook converts the logic from `fast_api_app.py` into an interactive comparison tool.\n",
    "It compares **OpenAI GPT-4.1** and **Google Gemini 2.5 Pro** on SDLC tasks (User Story Generation, etc.) and visualizes the results."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install dependencies\n",
    "%pip install fastapi uvicorn python-multipart pandas pdfplumber python-pptx python-docx toml langchain langchain-community langchain-huggingface langchain-openai langchain-google-genai faiss-cpu scikit-learn matplotlib seaborn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import hashlib\n",
    "import json\n",
    "import os\n",
    "import pickle\n",
    "import re\n",
    "import time\n",
    "from io import BytesIO\n",
    "import getpass\n",
    "\n",
    "import pandas as pd\n",
    "import pdfplumber\n",
    "import pptx\n",
    "import toml\n",
    "from docx import Document\n",
    "from langchain.chains.retrieval_qa.base import RetrievalQA\n",
    "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "\n",
    "# LLM Imports\n",
    "from langchain_google_genai import ChatGoogleGenerativeAI\n",
    "from langchain_openai import ChatOpenAI\n",
    "\n",
    "from pydantic import BaseModel\n",
    "from PyPDF2 import PdfReader\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Setup Directories\n",
    "VECTOR_STORE_DIR = \"./vector_stores\"\n",
    "GENERATION_CACHE_DIR = \"./generation_cache\"\n",
    "os.makedirs(VECTOR_STORE_DIR, exist_ok=True)\n",
    "os.makedirs(GENERATION_CACHE_DIR, exist_ok=True)\n",
    "\n",
    "# Global Storage\n",
    "uploaded_documents = {}\n",
    "vector_stores = {}\n",
    "generation_cache = {}\n",
    "\n",
    "# Configuration\n",
    "RETRIEVE_TOP_K = 6 \n",
    "CHUNK_SIZE = 1200\n",
    "CHUNK_OVERLAP = 200 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set API Keys\n",
    "# Ensure you have valid keys for GPT-4.1 and Gemini 2.5\n",
    "if \"OPENAI_API_KEY\" not in os.environ:\n",
    "    os.environ[\"OPENAI_API_KEY\"] = getpass.getpass(\"Enter OpenAI API Key: \")\n",
    "\n",
    "if \"GOOGLE_API_KEY\" not in os.environ:\n",
    "    os.environ[\"GOOGLE_API_KEY\"] = getpass.getpass(\"Enter Google Gemini API Key: \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Core Helper Functions (Text Extraction & Caching) ---\n",
    "\n",
    "def get_cache_key(document_id: str, artifact_type: str, input_text: str, model: str) -> str:\n",
    "    input_hash = hashlib.md5(input_text.encode()).hexdigest()[:16]\n",
    "    return f\"{document_id}_{artifact_type}_{model}_{input_hash}\"\n",
    "\n",
    "def extract_text_from_file(file_path: str) -> str:\n",
    "    \"\"\"Reads text from local file path.\"\"\"\n",
    "    text = \"\"\n",
    "    filename = os.path.basename(file_path)\n",
    "    file_ext = os.path.splitext(filename)[1].lower()\n",
    "    \n",
    "    with open(file_path, \"rb\") as f:\n",
    "        file_content = f.read()\n",
    "\n",
    "    if file_ext == \".pdf\":\n",
    "        try:\n",
    "            with pdfplumber.open(BytesIO(file_content)) as pdf:\n",
    "                for page in pdf.pages:\n",
    "                    text += (page.extract_text() or \"\") + \"\\n\"\n",
    "        except:\n",
    "            pdf_reader = PdfReader(BytesIO(file_content))\n",
    "            for page in pdf_reader.pages:\n",
    "                text += page.extract_text()\n",
    "    elif file_ext == \".docx\":\n",
    "        doc = Document(BytesIO(file_content))\n",
    "        for para in doc.paragraphs:\n",
    "            text += para.text + \"\\n\"\n",
    "    elif file_ext == \".txt\":\n",
    "        text = file_content.decode(\"utf-8\")\n",
    "    return text\n",
    "\n",
    "def create_vector_store(text: str) -> FAISS:\n",
    "    text_splitter = RecursiveCharacterTextSplitter(\n",
    "        separators=\"\\n\", chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP, length_function=len\n",
    "    )\n",
    "    chunks = text_splitter.split_text(text)\n",
    "    embeddings = HuggingFaceEmbeddings(model_name=\"sentence-transformers/all-MiniLM-L6-v2\")\n",
    "    return FAISS.from_texts(chunks, embeddings)\n",
    "\n",
    "def parse_json_output(text: str):\n",
    "    clean = text.strip()\n",
    "    fence = re.search(r\"```json\\s*(.*?)```\", clean, re.DOTALL) or re.search(r\"```\\s*(.*?)```\", clean, re.DOTALL)\n",
    "    if fence: clean = fence.group(1).strip()\n",
    "    try:\n",
    "        return json.loads(clean), None\n",
    "    except Exception as e:\n",
    "        return clean, str(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Scoring Metrics ---\n",
    "\n",
    "def calculate_confidence_level(prompt: str, answer: str) -> float:\n",
    "    try:\n",
    "        prompt_clean = re.sub(r'[^\\w\\s]', '', prompt.lower())\n",
    "        answer_clean = re.sub(r'[^\\w\\s]', '', answer.lower())\n",
    "        prompt_keywords = set(prompt_clean.split())\n",
    "        answer_words = set(answer_clean.split())\n",
    "        common_keywords = prompt_keywords.intersection(answer_words)\n",
    "        keyword_overlap = len(common_keywords) / len(prompt_keywords) if prompt_keywords else 0\n",
    "        vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)\n",
    "        if not prompt_clean or not answer_clean: return 0\n",
    "        tfidf_matrix = vectorizer.fit_transform([prompt_clean, answer_clean])\n",
    "        similarity_score = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]\n",
    "        confidence_score = (keyword_overlap * 0.3 + similarity_score * 0.7) * 100\n",
    "        return min(confidence_score, 100)\n",
    "    except:\n",
    "        return 0\n",
    "\n",
    "def calculate_match_percentage(answer: str, source_text: str) -> float:\n",
    "    try:\n",
    "        answer_clean = re.sub(r'[^\\w\\s]', '', answer.lower())\n",
    "        source_clean = re.sub(r'[^\\w\\s]', '', source_text.lower())\n",
    "        vectorizer = TfidfVectorizer(stop_words='english', max_features=1000, ngram_range=(1, 2))\n",
    "        tfidf_matrix = vectorizer.fit_transform([source_clean, answer_clean])\n",
    "        match_score = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]\n",
    "        return min(match_score * 100, 100)\n",
    "    except:\n",
    "        return 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Model Initialization ---\n",
    "# CORRECTED MODEL IDS for late 2025 context\n",
    "\n",
    "def initialize_llm(model_type=\"openai\"):\n",
    "    \"\"\"Initialize LLM based on type with corrected Dec 2025 model IDs.\"\"\"\n",
    "    if model_type == \"openai\":\n",
    "        return ChatOpenAI(\n",
    "            model=\"gpt-4.1\",  # Corrected from 'Open AI GPT 4.1'\n",
    "            temperature=0.5,\n",
    "        )\n",
    "    elif model_type == \"gemini\":\n",
    "        return ChatGoogleGenerativeAI(\n",
    "            model=\"gemini-2.5-pro\", # Corrected to latest 2025 Gemini model\n",
    "            temperature=0.5,\n",
    "            convert_system_message_to_human=True\n",
    "        )\n",
    "    else:\n",
    "        raise ValueError(\"Unknown model type\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Comparison Engine ---\n",
    "\n",
    "def run_model_comparison(document_id: str, prompt_template: str, task_name: str):\n",
    "    \"\"\"\n",
    "    Runs the provided prompt against both GPT and Gemini models \n",
    "    and returns a comparison dictionary.\n",
    "    \"\"\"\n",
    "    if document_id not in uploaded_documents:\n",
    "        print(\"Document not found.\")\n",
    "        return None\n",
    "\n",
    "    text = uploaded_documents[document_id][\"text\"]\n",
    "    vector_store = vector_stores[document_id]\n",
    "    \n",
    "    results = []\n",
    "    models_to_test = [\"openai\", \"gemini\"]\n",
    "    \n",
    "    for model_name in models_to_test:\n",
    "        print(f\"Running {task_name} with {model_name}...\")\n",
    "        \n",
    "        try:\n",
    "            llm = initialize_llm(model_name)\n",
    "            qa_chain = RetrievalQA.from_chain_type(\n",
    "                llm=llm,\n",
    "                chain_type=\"stuff\",\n",
    "                retriever=vector_store.as_retriever(search_kwargs={\"k\": RETRIEVE_TOP_K})\n",
    "            )\n",
    "            \n",
    "            start_time = time.time()\n",
    "            response = qa_chain.invoke({\"query\": prompt_template})\n",
    "            output_text = response['result']\n",
    "            processing_time = time.time() - start_time\n",
    "            \n",
    "            confidence = calculate_confidence_level(prompt_template, output_text)\n",
    "            match_score = calculate_match_percentage(output_text, text)\n",
    "            overall = (confidence + match_score) / 2\n",
    "            \n",
    "            results.append({\n",
    "                \"Model\": model_name,\n",
    "                \"Task\": task_name,\n",
    "                \"Processing Time (s)\": round(processing_time, 2),\n",
    "                \"Confidence Score\": round(confidence, 2),\n",
    "                \"Match Score\": round(match_score, 2),\n",
    "                \"Overall Score\": round(overall, 2),\n",
    "                \"Output\": output_text\n",
    "            })\n",
    "        except Exception as e:\n",
    "            print(f\"Error with {model_name}: {e}\")\n",
    "            results.append({\n",
    "                \"Model\": model_name,\n",
    "                \"Task\": task_name,\n",
    "                \"Processing Time (s)\": 0,\n",
    "                \"Confidence Score\": 0,\n",
    "                \"Match Score\": 0,\n",
    "                \"Overall Score\": 0,\n",
    "                \"Output\": str(e)\n",
    "            })\n",
    "        \n",
    "    return pd.DataFrame(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Visualization ---\n",
    "\n",
    "def visualize_comparison(df):\n",
    "    \"\"\"Generates bar charts for model comparison.\"\"\"\n",
    "    if df is None or df.empty:\n",
    "        print(\"No data to visualize.\")\n",
    "        return\n",
    "\n",
    "    sns.set_theme(style=\"whitegrid\")\n",
    "    \n",
    "    # 1. Score Comparison\n",
    "    metrics = [\"Confidence Score\", \"Match Score\", \"Overall Score\"]\n",
    "    df_melted = df.melt(id_vars=[\"Model\"], value_vars=metrics, var_name=\"Metric\", value_name=\"Score\")\n",
    "    \n",
    "    plt.figure(figsize=(10, 6))\n",
    "    sns.barplot(data=df_melted, x=\"Metric\", y=\"Score\", hue=\"Model\", palette=\"viridis\")\n",
    "    plt.title(\"Quality Assessment: GPT-4.1 vs Gemini 2.5\")\n",
    "    plt.ylim(0, 100)\n",
    "    plt.show()\n",
    "    \n",
    "    # 2. Time Comparison\n",
    "    plt.figure(figsize=(6, 5))\n",
    "    sns.barplot(data=df, x=\"Model\", y=\"Processing Time (s)\", hue=\"Model\", palette=\"magma\", legend=False)\n",
    "    plt.title(\"Processing Speed: GPT-4.1 vs Gemini 2.5\")\n",
    "    plt.show()\n",
    "\n",
    "    # Best Model Logic\n",
    "    best_model = df.loc[df[\"Overall Score\"].idxmax()]\n",
    "    print(f\"\\n🏆 Best Performing Model: {best_model['Model'].upper()}\")\n",
    "    print(f\"Overall Score: {best_model['Overall Score']}\")\n",
    "    print(\"-\" * 50)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- Execution ---\n",
    "\n",
    "# 1. Create a dummy BRD file for demonstration\n",
    "file_path = \"sample_brd.txt\"\n",
    "if not os.path.exists(file_path):\n",
    "    with open(file_path, \"w\") as f:\n",
    "        f.write(\"\"\"BRD: Login System\n",
    "        1. The system shall allow users to login using Email and Password.\n",
    "        2. The system shall support Two-Factor Authentication (2FA) via SMS.\n",
    "        3. Passwords must be at least 12 characters long.\n",
    "        4. Admin users should be able to reset user passwords.\n",
    "        \"\"\")\n",
    "    print(f\"Created dummy file: {file_path}\")\n",
    "\n",
    "# 2. Process Document\n",
    "text = extract_text_from_file(file_path)\n",
    "doc_id = os.path.basename(file_path).replace(\".\", \"_\")\n",
    "uploaded_documents[doc_id] = {\"text\": text}\n",
    "vector_stores[doc_id] = create_vector_store(text)\n",
    "\n",
    "# 3. Define Prompt\n",
    "user_story_prompt = \"\"\"\n",
    "You are an Expert Business Analyst.\n",
    "Extract EVERY POSSIBLE user story from the BRD below. \n",
    "Format as JSON: {\"user_stories\": [{\"id\": \"...\", \"story\": \"...\", \"acceptance_criteria\": [...]}]}\n",
    "\"\"\"\n",
    "\n",
    "# 4. Run Comparison\n",
    "print(\"\\nStarting Model Comparison (GPT-4.1 vs Gemini 2.5)...\")\n",
    "df_results = run_model_comparison(doc_id, user_story_prompt, \"User Story Gen\")\n",
    "\n",
    "# 5. Visualize\n",
    "display(df_results[[\"Model\", \"Processing Time (s)\", \"Confidence Score\", \"Match Score\", \"Overall Score\"]])\n",
    "visualize_comparison(df_results)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

# Write to file
filename = 'SDLC_Automate_Comparison.ipynb'
with open(filename, 'w') as f:
    json.dump(notebook_content, f, indent=2)

print(f"✅ Successfully created {filename}")